import "./globals.css";
import type { Metadata } from "next";
import { VT323 } from "next/font/google";

const vT323 = VT323({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "windows 98",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${vT323.className} h-screen`}>{children}</body>
    </html>
  );
}
